package: nbpresent

platform:
  - linux-32
  - linux-64
  - osx-64
  - win-32
  - win-64

engine:
  - python=2.7
  - python=3.4
  - python=3.5

script:
  - conda build . -c anaconda-nb-extensions

build_targets: conda
