package:
  name: anaconda-nb-extensions-meta-config
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: .

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  always_include_files:
    - {{ environ.get('PREFIX') }}/etc/jupyter/*.json
    - {{ environ.get('PREFIX') }}/etc/jupyter/*/*.json

requirements:
  build:
    - python
    - notebook <5
    - nbpresent
    - nb_anacondacloud
    - nb_conda_kernels
    - nb_conda
    - nbsetuptools
    - nb_config_manager

about:
  summary: A configuration metapackage for enabling Anaconda-bundled jupyter extensions
  home: https://github.com/Anaconda-Server/anaconda-installer-nb-extension
  license_file: LICENSE
  license: BSD License
